/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/final_7.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.005}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.male_genericMesh_1.geometry}
          material={materials.material0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.male_genericMesh_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/final_7.glb");
